# Generated by Django 2.2.16 on 2022-09-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220922_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
